# Generated by Django 4.1.3 on 2022-11-18 14:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdur', models.IntegerField()),
                ('ccat', models.CharField(max_length=50)),
                ('cprice', models.IntegerField()),
            ],
            managers=[
                ('ccustomobj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('is_deleted', models.CharField(max_length=10)),
            ],
        ),
    ]
